Repository auth0/auth0-angular, pull requests merged in 2020-10, with the labels that each got.

#65 Add contact links to issue templates
  .github/ISSUE_TEMPLATE/config.yml
  FAQ.md
Labels: documentation, review:small

#62 [SDK-1976] Async alternative for AuthModule.forRoot
  README.md
  package-lock.json
  package.json
  projects/auth0-angular/src/lib/abstract-navigator.ts
  projects/auth0-angular/src/lib/auth.client.spec.ts
  projects/auth0-angular/src/lib/auth.client.ts
  projects/auth0-angular/src/lib/auth.config.spec.ts
  projects/auth0-angular/src/lib/auth.config.ts
  projects/auth0-angular/src/lib/auth.module.ts
  projects/playground/src/app/app.module.ts
Labels: CH: Added, enhancement, review:small

#71 Ensure interceptor uses AuthClientConfig
  projects/auth0-angular/src/lib/auth.interceptor.spec.ts
  projects/auth0-angular/src/lib/auth.interceptor.ts
Labels: CH: Fixed, review:small

#69 Get id token claims
  README.md
  projects/auth0-angular/src/lib/auth.service.spec.ts
  projects/auth0-angular/src/lib/auth.service.ts
  projects/playground/e2e/integration/playground.spec.ts
  projects/playground/src/app/app.component.html
  projects/playground/src/app/app.component.ts
Labels: CH: Added
