Repository auth0/auth0-angular, pull requests merged in 2020-09, with the labels that each got.

#42 [SDK-1923] Improve readability of Calling an API section in the readme
  README.md
Labels: documentation, review:small

#46 [SDK-1931] Add information regarding use inside Angular Universal projects
  README.md
Labels: documentation, review:small

#45 [SDK-1931] Add support for canActivateChild and canLoad in AuthGuard
  package-lock.json
  projects/auth0-angular/src/lib/auth.guard.spec.ts
  projects/auth0-angular/src/lib/auth.guard.ts
  projects/playground/e2e/integration/playground.spec.ts
  projects/playground/src/app/app-routing.module.ts
  projects/playground/src/app/app.component.html
  projects/playground/src/app/app.module.ts
  projects/playground/src/app/components/child-route.component.ts
  projects/playground/src/app/components/lazy-module.component.ts
  projects/playground/src/app/components/nested-child-route.component.ts
  projects/playground/src/app/components/protected.component.ts
  projects/playground/src/app/components/unprotected.component.ts
  projects/playground/src/app/lazy-module-routing.module.ts
  projects/playground/src/app/lazy-module.module.ts
  projects/playground/src/app/protected/protected.component.css
  projects/playground/src/app/protected/protected.component.html
  projects/playground/src/app/protected/protected.component.spec.ts
  projects/playground/src/app/unprotected/unprotected.component.css
  projects/playground/src/app/unprotected/unprotected.component.html
  projects/playground/src/app/unprotected/unprotected.component.spec.ts
Labels: CH: Added, dependencies, enhancement, review:medium

#49 [SDK-1921] ng-add support
  README.md
  docs/classes/abstractnavigator.html
  docs/classes/auth0clientfactory.html
  docs/classes/authguard.html
  docs/classes/authhttpinterceptor.html
  docs/classes/authmodule.html
  docs/classes/authservice.html
  docs/globals.html
  docs/index.html
  docs/interfaces/authconfig.html
  docs/interfaces/httpinterceptorconfig.html
  docs/interfaces/httpinterceptorrouteconfig.html
  package.json
  projects/auth0-angular/package.json
  projects/auth0-angular/schematics/collection.json
  projects/auth0-angular/schematics/ng-add/index.ts
  projects/auth0-angular/tsconfig.schematics.json
Labels: CH: Added, feature request, review:small

#48 [SDK-1895] Add options to match HTTP requests based on HTTP method
  README.md
  projects/auth0-angular/src/lib/abstract-navigator.spec.ts
  projects/auth0-angular/src/lib/abstract-navigator.ts
  projects/auth0-angular/src/lib/auth.config.ts
  projects/auth0-angular/src/lib/auth.interceptor.spec.ts
  projects/auth0-angular/src/lib/auth.interceptor.ts
  projects/auth0-angular/src/lib/auth.module.ts
  projects/auth0-angular/src/lib/auth.service.spec.ts
  projects/auth0-angular/src/lib/auth.service.ts
  projects/auth0-angular/src/lib/window.ts
  projects/playground/src/app/app.component.spec.ts
  projects/playground/src/app/app.component.ts
Labels: CH: Changed, review:small

#51 Add error handling capability
  README.md
  projects/auth0-angular/src/lib/auth.service.spec.ts
  projects/auth0-angular/src/lib/auth.service.ts
  projects/playground/src/app/app.component.html
  projects/playground/src/app/app.component.ts
Labels: CH: Added, review:small

#57 Update docs to match latest release
  docs/classes/abstractnavigator.html
  docs/classes/auth0clientfactory.html
  docs/classes/authguard.html
  docs/classes/authhttpinterceptor.html
  docs/classes/authmodule.html
  docs/classes/authservice.html
  docs/enums/httpmethod.html
  docs/globals.html
  docs/index.html
  docs/interfaces/authconfig.html
  docs/interfaces/httpinterceptorconfig.html
  docs/interfaces/httpinterceptorrouteconfig.html
Labels: review:tiny

#58 Add MIT license file
  LICENSE
  README.md
Labels: review:tiny
