Repository auth0/auth0-angular, pull requests merged in 2020-08, with the labels that each got.

#32 Improve the wording used in some docs
  README.md
  projects/auth0-angular/src/lib/auth.config.ts
Labels: review:tiny

#28 Miscellaneous fixes and tweaks
  README.md
  projects/auth0-angular/src/lib/auth.interceptor.spec.ts
  projects/auth0-angular/src/lib/auth.interceptor.ts
  projects/auth0-angular/src/lib/auth.module.ts
  projects/auth0-angular/src/lib/auth.service.ts
  projects/playground/src/app/app.module.ts
Labels: review:small

#29 Remove Regex support from the HTTP interceptor
  projects/auth0-angular/src/lib/auth.config.ts
  projects/auth0-angular/src/lib/auth.interceptor.spec.ts
  projects/auth0-angular/src/lib/auth.interceptor.ts
Labels: CH: Removed, review:small

#34 Update readme to include Beta labelling
  README.md
Labels: CH: Changed, review:tiny

#35 Add metadata to package
  projects/auth0-angular/package.json
Labels: CH: Changed

#36 Make the "publish" script copy the README file
  scripts/publish.js
Labels: CH: Changed, review:tiny

#38 Add changelog of the first EA release
  CHANGELOG.md
Labels: CH: Changed, review:tiny

#39 Fix publish script using the new release version
  scripts/publish.js
  scripts/release.js
Labels: CH: Fixed, review:tiny

#40 Update Readme with more badges and rewording of expectations
  README.md
Labels: documentation

#41 Remove use of regex in API example snippets
  README.md
Labels: documentation
