Repository auth0/auth0-angular, pull requests merged in 2021-09, with the labels that each got.

#208 Use the new release automation solution
  .shiprc
  package.json
  scripts/changelog.js
  scripts/cleanup.js
  scripts/release.js
Labels: review:tiny

#209 Do not redirect AuthGuard when user is already authenticated
  projects/auth0-angular/src/lib/auth.service.spec.ts
  projects/auth0-angular/src/lib/auth.state.ts
Labels: CH: Fixed, review:small

#215 [SDK-2786] Ensure SDK works when useHash is true
  projects/auth0-angular/src/lib/auth.service.spec.ts
  projects/auth0-angular/src/lib/auth.service.ts
Labels: CH: Fixed, review:small

#218 Bump Auth0-SPA-JS to 1.18.0
  package-lock.json
  package.json
Labels: CH: Added, review:tiny

#219 Release v1.7.0
  CHANGELOG.md
  docs/classes/abstract_navigator.abstractnavigator.html
  docs/classes/auth_client.auth0clientfactory.html
  docs/classes/auth_config.authclientconfig.html
  docs/classes/auth_guard.authguard.html
  docs/classes/auth_interceptor.authhttpinterceptor.html
  docs/classes/auth_module.authmodule.html
  docs/classes/auth_service.authservice.html
  docs/classes/auth_state.authstate.html
  docs/enums/auth_config.httpmethod.html
  docs/interfaces/auth_config.authconfig.html
  docs/interfaces/auth_config.httpinterceptorconfig.html
  docs/interfaces/auth_config.httpinterceptorrouteconfig.html
  docs/modules/auth_client.html
  docs/modules/auth_config.html
  projects/auth0-angular/package.json
  projects/auth0-angular/src/useragent.ts
Labels: review:small

#223 Add connection property to auth.config.ts
  projects/auth0-angular/src/lib/auth.config.ts
Labels: CH: Fixed, review:tiny
