Repository auth0/auth0-angular, pull requests merged in 2021-02, with the labels that each got.

#121 Update readme and playground for dynamic configuration
  README.md
  projects/playground/src/app/app.module.ts
  projects/playground/src/assets/config.json
Labels: review:small

#125 Update Readme regarding dynamic configuration
  README.md
Labels: review:tiny

#123 Enable strict mode
  projects/auth0-angular/src/lib/abstract-navigator.ts
  projects/auth0-angular/src/lib/auth.config.ts
  projects/auth0-angular/src/lib/auth.guard.ts
  projects/auth0-angular/src/lib/auth.interceptor.spec.ts
  projects/auth0-angular/src/lib/auth.interceptor.ts
  projects/auth0-angular/src/lib/auth.service.spec.ts
  projects/auth0-angular/src/lib/auth.service.ts
  projects/playground/src/app/app.component.spec.ts
  tsconfig.base.json
Labels: CH: Changed, review:medium
