Repository auth0/auth0-angular, pull requests merged in 2021-12, with the labels that each got.

#243 Update peerDependencies to support Angular 13
  projects/auth0-angular/package.json
Labels: review:tiny, CH: Changed

#245 Update Auth0-SPA-JS to 1.19.3
  package-lock.json
  package.json
Labels: review:tiny

#240 App state interface
  projects/auth0-angular/src/lib/auth.config.ts
  projects/auth0-angular/src/lib/auth.service.ts
Labels: CH: Changed

#247 Avoid using jfrog for npm packages
  package-lock.json
Labels: review:tiny

#256 Avoid using jfrog for npm packages
  package-lock.json
Labels: review:tiny
