Repository auth0/auth0-angular, pull requests merged in 2021-05, with the labels that each got.

#151 Replace integration test password with environment variable
  README.md
  projects/playground/e2e/integration/playground.spec.ts
Labels: enhancement, review:tiny

#150 [SDK-2542] Expose methods from Auth0 SPA SDK
  package-lock.json
  projects/auth0-angular/src/lib/auth.service.spec.ts
  projects/auth0-angular/src/lib/auth.service.ts
Labels: CH: Added, review:small

#152 Release v1.5.0
  CHANGELOG.md
  docs/assets/js/search.json
  docs/classes/abstractnavigator.html
  docs/classes/auth0clientfactory.html
  docs/classes/authclientconfig.html
  docs/classes/authguard.html
  docs/classes/authhttpinterceptor.html
  docs/classes/authmodule.html
  docs/classes/authservice.html
  docs/enums/httpmethod.html
  docs/globals.html
  docs/index.html
  docs/interfaces/authconfig.html
  docs/interfaces/httpinterceptorconfig.html
  docs/interfaces/httpinterceptorrouteconfig.html
  projects/auth0-angular/package.json
  projects/auth0-angular/src/useragent.ts
Labels: review:small

#158 Add support for Angular 12
  angular.json
  package-lock.json
  package.json
  projects/auth0-angular/package.json
  projects/auth0-angular/src/test.ts
  projects/playground/src/environments/environment.ts
  projects/playground/src/polyfills.ts
  projects/playground/src/test.ts
Labels: review:small

#161 Release v1.5.1
  CHANGELOG.md
  projects/auth0-angular/package.json
  projects/auth0-angular/src/useragent.ts
Labels: review:tiny

#160 Update typedoc to support TypeScript 4.2
  docs/assets/css/main.css
  docs/assets/js/main.js
  docs/assets/js/search.js
  docs/assets/js/search.json
  docs/classes/abstract_navigator.abstractnavigator.html
  docs/classes/abstractnavigator.html
  docs/classes/auth0clientfactory.html
  docs/classes/auth_client.auth0clientfactory.html
  docs/classes/auth_config.authclientconfig.html
  docs/classes/auth_guard.authguard.html
  docs/classes/auth_interceptor.authhttpinterceptor.html
  docs/classes/auth_module.authmodule.html
  docs/classes/auth_service.authservice.html
  docs/classes/authclientconfig.html
  docs/classes/authguard.html
  docs/classes/authhttpinterceptor.html
  docs/classes/authmodule.html
  docs/classes/authservice.html
  docs/enums/auth_config.httpmethod.html
  docs/enums/httpmethod.html
  docs/globals.html
  docs/index.html
  docs/interfaces/auth_config.authconfig.html
  docs/interfaces/auth_config.httpinterceptorconfig.html
  docs/interfaces/auth_config.httpinterceptorrouteconfig.html
  docs/interfaces/authconfig.html
  docs/interfaces/httpinterceptorconfig.html
  docs/interfaces/httpinterceptorrouteconfig.html
  docs/modules.html
  docs/modules/abstract_navigator.html
  docs/modules/auth_client.html
  docs/modules/auth_config.html
  docs/modules/auth_guard.html
  docs/modules/auth_interceptor.html
  docs/modules/auth_module.html
  docs/modules/auth_service.html
  package-lock.json
  package.json
  typedoc.json
Labels: review:small
