Repository auth0/auth0-angular, pull requests merged in 2021-04, with the labels that each got.

#142 [SDK-2456] Remove Organizations beta labelling
  README.md
  docs/assets/js/main.js
  docs/classes/abstractnavigator.html
  docs/classes/auth0clientfactory.html
  docs/classes/authclientconfig.html
  docs/classes/authguard.html
  docs/classes/authhttpinterceptor.html
  docs/classes/authmodule.html
  docs/classes/authservice.html
  docs/enums/httpmethod.html
  docs/globals.html
  docs/index.html
  docs/interfaces/authconfig.html
  docs/interfaces/httpinterceptorconfig.html
  docs/interfaces/httpinterceptorrouteconfig.html
  projects/auth0-angular/src/lib/auth.config.ts
Labels: documentation

#131 Only emit user$ and idTokenClaims$ when login, logout or token changed
  projects/auth0-angular/src/lib/auth.service.ts
Labels: review:small

#147 Update FAQ to include querystring for appState.target
  FAQ.md
Labels: review:small

#145 [SDK-2482] Add allowAnonymous option to HttpInterceptor config
  README.md
  projects/auth0-angular/src/lib/auth.config.ts
  projects/auth0-angular/src/lib/auth.interceptor.spec.ts
  projects/auth0-angular/src/lib/auth.interceptor.ts
Labels: CH: Added, review:small

#146 Add API to be used with playground
  README.md
  api-server.js
  package-lock.json
  package.json
  projects/playground/src/app/app.component.html
  projects/playground/src/app/app.component.spec.ts
  projects/playground/src/app/app.component.ts
  projects/playground/src/assets/config.json
Labels: review:small

#148 Release 1.4.1
  CHANGELOG.md
  docs/assets/js/search.json
  docs/classes/abstractnavigator.html
  docs/classes/auth0clientfactory.html
  docs/classes/authclientconfig.html
  docs/classes/authguard.html
  docs/classes/authhttpinterceptor.html
  docs/classes/authmodule.html
  docs/classes/authservice.html
  docs/enums/httpmethod.html
  docs/globals.html
  docs/index.html
  docs/interfaces/authconfig.html
  docs/interfaces/httpinterceptorconfig.html
  docs/interfaces/httpinterceptorrouteconfig.html
  projects/auth0-angular/package.json
  projects/auth0-angular/src/useragent.ts
Labels: review:small
